// frontend/js/ubicaciones.js
export const departamentosYLocalidades = {
    "Aguirre": [
        "Pinto",
        "Argentina",
        "Casares",
        "Malbran",
    ],
    "Alberdi": [
        "Campo Gallo",
        "Donadeu",
        "Huachana",
        "Sacháyoj",
        "Santos Lugares",
    ],
    "Atamisqui": [
        "Villa Atamisqui",
        "Estación Atamisqui",
        "Hoyón",
        "Juanillo",
        "Medellín",
    ],
    "Avellaneda": [
        "Herrera",
        "Colonia Dora",
        "Icaño",
        "Lugones",
        "Punta Pozo",
        "Real Sayana",
        "Villa Mailín"
    ],
    "Banda": [
        "La Banda",
        "Clodomira",
        "Abra Grande",
        "Antajé",
        "Ardiles",
        "Cañada Escobar",
        "Chaupi Pozo",
        "El Aibe",
        "Estación Simbolar",
        "Los Quiroga",
        "La Auroda",
        "La Darsena",
        "Negra Muerta",
    ],
    "Belgrano": [
        "Bandera",
        "Cuatros Bocas",
        "Fortín Inca",
        "Guardia Escolta",
    ],
    "Choya": [
        "Frías",
        "Choya",
        "Laprida",
        "Tapso",
        "Villa La Punta",
    ],
    "Copo": [
        "Monte Quemado",
        "Pampa de los Guanacos",
        "Ahi Veremos",
        "El Caburé",
        "Los Piripintos",
        "San José del Boquerón",
        "Villa Matoque",
    ],
    "Figueroa": [
        "La Cañada",
        "Bandera Bajada",
        "Caspi Corral-San Antonio",
        "Colonia San Juan",
        "La Cañada",
        "La Invernada",
        "Vaca Huañuna",
        "Villa Figueroa",
    ],
    "General Taboada": [
        "Añatuya",
        "Los Juries",
        "Averías",
        "Estación Tacañitas",
        "La Simona",
        "La Nena",
        "Tomás Young",
    ],
    "Guasayán": [
        "San Pedro de Guasayán",
        "Doña Luisa",
        "Guampacha",
        "Lavalle",
        "Santa Catalina",
        "Villa Guasayán",
    ],
    "Jiménez": [
        "Pozo Hondo",
        "El Arenal",
        "El Bobadal",
        "El Charco",
        "Gramilla",
        "Tres Cruces",
    ],
    "Juan Felipe Ibarra": [
        "Suncho Corral",
        "El Colorado",
        "Matará",
        "Melero",
        "Pozo del Toba",
        "San Antonio - Roldán",
        "Vilelas",
        "Yuchán",
    ],
    "Juan Francisco Borges": [
        "Santiago del Estero",
        "El Deán",
        "Remes",
        "San Benito",
        "San Pedro",
        "Santa María",
        "Sol de Mayo",
        "El Zanjón",
        "Macon",
        "Maquito",
        "Mal Paso",
        "Puestito San Antonio",
        "Yanda",
        "Vuelta de la Barranca",
    ],
    
    "Loreto": [
        "Loreto",
        "La Noria",
        "San Vicente",
        "Sauce Solo",
        "Tío Pozo",
    ],
    "Mtre": [
        "Villa Unión",
        "Fuerte Esperanza",
        "Abras",
        "Unión",
        "Captaros",
        "Porongos",
    ],
    
    "Moreno": [
        "Quimilí",
        "Tintina",
        "Amamá",
        "Pampa Pozo",
        "Santo Domingo",
        "Granadero Gatica",
        "Las Tinajas",
        "Libertad",
        "Lilo Viejo - Patay",
        "Otumpa",
        "Villa Brana",
        "Weisburd",
    ],
    "Ojo de Agua": [
        "Villa Ojo de Agua",
        "Sol de Julio",
        "El 49",
        "Ambargasta",
    ],
    "Pellegrini": [
        "Nueva Esperanza",
        "Ahi Veremos",
        "Campo Grande",
        "El Mojón",
        "Las Delicias",
        "Pozo Betbeder",
        "Quebracho Coto",
        "Rapelli",
        "Santo Domingo",
        "Villa Mercedes",
    ],
    "Quebrachos": [
        "Sumampa",
        "Ramirez de Velazco",
    ],
    "Río Hondo": [
        "Termas de Río Hondo",
        "Acos - Pozo del Arbolito",
        "Amicha",
        "Colonia Tinco",
        "El Sauzal",
        "Lezcano",
        "Los Nuñez",
        "Los Ovejeros",
        "Pozuelos",
        "Sotelo",
        "Villa Río Hondo",
        "Vinará",
    ],
    "Rivadavia": [
        "Selva",
        "Colonia Alpina",
        "Palo Negro",
    ],
    "Robles": [
        "Fernández",
        "Beltrán",
        "Ingeniero Forres",
        "Colonia El Simbolar",
        ""
    ],
    "Salavina": [
        "Los Telares",
        "Chilca Juliana",
        "La Paliza",
        "Sabagasta",
        "Vaca Human",
        "Villa Salavina",
    ],
    "San Martín": [
        "Brea Pozo",
        "Átoj Pozo",
        "Estación Robles",
        "Estación Taboada",
        "Villa Nueva",
    ],
    "Sarmiento": [
        "Garza",
        "Matará",
        "Sauce Bajada",
        "Guaypé",        
    ],
    "Silipica": [
        "Árraga",
        "Nueva Francia",
        "Manogasta",
        "Villa Silipica"
    ],
};